### ISSUE TITLE
Create dev environment

### ISSUE THREAD

**Issue by mthomas-ketchbrook** [COHHIO/ryha#104]
## Proposal

For the purposes of testing (especially testing file uploads) during development, we advocating for the creation of a "dev" environment.

We are proposing a local, Docker-ized approach to this development environment, utilizing VSCode Devcontainers and Docker/Docker Compose.

## Architecture

The following diagram represents the proposed architecture for the dev environment.

```mermaid
flowchart TB
    subgraph Devcontainer
        direction TB
        A[Dockerfile for app]
        B[Dockerfile for PostgreSQL\ndatabase]
        C[Docker compose]
    end
    subgraph Services
    direction LR
        D[(PostgreSQL Database)]
        E(Shiny App)
    end
    F["Redacted test .zip file"]
A --> C
B --> C
Devcontainer --> Services
D <-- mounted ---> E
F -.-> Services
``` 

## Advantages

Utilizing this architecture will avoid spinning up any cloud resources (i.e., zero cost, do not need to whitelist IP addresses), ensure the testing data does not make it to any cloud environments, and ensure consistency of environment across collaborators on the project.

## Drawbacks

Utilizing this architecture adds some additional complexity and dependencies.  While the complexity can be mitigated through documentation, the additional software dependencies (VSCode and Docker / Docker Compose) will need to be installed by developers on this project.

Further, while developers on this codebase can have certainty that they are working within the same environment configuration, the local environment may *not* line up with the shinyapps.io environment (i.e., the production environment for the app).

**Comment by IvanM26** [comment]
Solved in #105
