### ISSUE TITLE
Bucket "Living Situation" categories

### ISSUE THREAD

**Issue by mthomas-ketchbrook** [COHHIO/ryha#40]
A first pass at this was incorporated into the latest release of the app, but additional changes have been proposed since then.

**Comment by mthomas-ketchbrook** [comment]
A first pass at this was incorporated into the latest release of the app, but additional changes have been proposed since then.

**Comment by mthomas-ketchbrook** [comment]
Buckets:

- [ ] no buckets for "Entry" items, only "Exit"
- [ ] condense the "Category" and "GeneralCategory" columns into a single column called "ExitCategory"
- [ ] change code 2 ("Transitional...") bucket to be "Temporary"

Donut charts:

- [ ] revert back to unique items (no bucketed "categories") for the first two donut charts (entry & exit)
- [ ] create a second chart (chart type TBD) that shows the "bucketed" living situation categories, or perhaps the individual items grouped by the buckets (e.g., grouped bar chart)

Sankey chart:

- [ ] remove sankey chart

**Comment by mthomas-ketchbrook** [comment]
Page 106 of [this document](https://files.hudexchange.info/resources/documents/HMIS-Data-Dictionary-2024.pdf) provides the new categories for each Living Situation item (for "Prior", "Current", and "Destination").

**Comment by IvanM26** [comment]
Solved in #63
