### ISSUE TITLE
Fix tooltip overflow

### ISSUE THREAD

**Issue by IvanM26** [COHHIO/ryha#99]
The categories present in the new "Destination" chart in "Living Situation" tab are very long and they are overflowing (see attached image below). It would be good to implement "word wrap" multi-line tooltips to avoid screen overflowing.

![long_echarts4r_tooltip](https://github.com/COHHIO/ryha/assets/60263844/7571c9a8-fc27-4388-99ea-1c8be3810277)

We can leverage the use of the  [`confine` parameter of the `tooltip` element](https://echarts.apache.org/en/option.html#tooltip.confine) to solve this problem.

**Comment by mthomas-ketchbrook** [comment]
Closed by #102
